# Generated by Django 6.0.1 on 2026-02-04 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TomatoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='专注任务', max_length=255, verbose_name='任务名称')),
                ('planned_duration', models.PositiveIntegerField(default=25, verbose_name='计划时长(分钟)')),
                ('work_start_at', models.DateTimeField(blank=True, null=True, verbose_name='工作开始时间')),
                ('work_end_at', models.DateTimeField(blank=True, null=True, verbose_name='工作结束时间')),
                ('leave_start_at', models.DateTimeField(blank=True, null=True, verbose_name='暂离开始时间')),
                ('leave_end_at', models.DateTimeField(blank=True, null=True, verbose_name='暂离结束时间')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('working', '进行中'), ('paused', '已暂停（暂离中）'), ('completed', '已完成'), ('abandoned', '已放弃')], default='planned', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomato_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '番茄钟会话',
                'verbose_name_plural': '番茄钟会话',
                'ordering': ['-created_at'],
            },
        ),
    ]
